image:
	docker build -t offline-job:v0.0.1 .

remote: image
	docker tag offline-job:v0.0.1 registry.cn-hangzhou.aliyuncs.com/charstal/offline-job:v0.0.1
	docker push registry.cn-hangzhou.aliyuncs.com/charstal/offline-job:v0.0.1