apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-monitor-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-monitor
  template:
    metadata:
      labels:
        app: load-monitor
    spec:
      containers:
      - name: load-monitor
        imagePullPolicy: Always
        image: registry.cn-hangzhou.aliyuncs.com/charstal/load-monitor:v0.0.2
        ports:
          - name: http
            containerPort: 2020
        env:
          - name: INFLUXDB_URL
            value: http://192.168.30.154:8086
          - name: METRICS_PROVIDER_NAME
            value: Prometheus
          - name: METRICS_PROVIDER_ADDRESS
            value: http://192.168.30.154:31190
          - name: LOG_LEVEL
            value: debug
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: load-monitor
  name: load-monitor-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    app: load-monitor