apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-monitor-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-monitor
  template:
    metadata:
      labels:
        app: load-monitor
    spec:
      containers:
      - name: load-monitor
        imagePullPolicy: Always
        image: registry.cn-hangzhou.aliyuncs.com/charstal/load-monitor:v0.0.1
        ports:
          - name: http
            containerPort: 2020
        env:
          # - name: INFLUXDB_URL
          #   value: 192.168.122.67:8086
          # - name: INFLUXDB_TOKEN
          #   value: YEkyUh-YUJ6pfV3Tf996_uHQan_szSihhTxdgxGf9HDMxQ2AXin5UqXN7EoKeHDaM9p12yKOngeD-OrbKf0zTA==
          # - name: INFLUXDB_ORG
          #   value: mo
          - name: REMOTE_BASE_DIR
            value: tmp/offline
          - name: LOCAL_BASE_DIR
            value: tmp/statistics
          - name: METRICS_PROVIDER_NAME
            value: Prometheus
          # - name: METRICS_PROVIDER_ADDRESS
          #   value: http://prometheus-k8s.monitoring.svc.cluster.local:9090
          - name: LOG_LEVEL
            value: debug
        volumeMounts:
        - name: nfs
          mountPath: "/bin/tmp"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: load-monitor-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: load-monitor
  name: load-monitor-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    app: load-monitor
