apiVersion: batch/v1
kind: Job
metadata:
  name: offline-job
spec:
  template:
    spec:
      containers:
      - name: offline
        imagePullPolicy: Always
        image: registry.cn-hangzhou.aliyuncs.com/charstal/offline-job:v0.0.1
        env:
          - name: LOAD_MONITOR_JOB_URL
            value: http://load-monitor-svc.default.svc.cluster.local:2020/job
      restartPolicy: Never