apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmp-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tmp-nfs
  nfs:
    path: /mnt/nfsfile/tmp
    server: 192.168.122.67
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: load-monitor-pvc
spec:
  storageClassName: tmp-nfs
  accessModes:
  - ReadWriteMany  #读写模式
  resources:
    requests:
      storage: 1G
